# Default initial positions for agbot_arm's ros2_control fake system

initial_positions:
  arm_base_joint: 0
  base_rail_to_ mid_rail_joint: 0
  elbow_joint: 0
  gripper_right_joint: 0
  mid_rail_to_arm_car_joint: 0
  shoulder_joint: 0
  wrist_joint: 0