# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    prismatic_joint_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

prismatic_joint_position_controller:
  ros__parameters:
    joints:
      - base_rail_to_ mid_rail_joint
      - mid_rail_to_arm_car_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
arm_controller:
  ros__parameters:
    joints:
      - mid_rail_to_arm_car_joint
      - arm_base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joints:
      - wrist_joint
      - gripper_right_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity