<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="agbot_arm">


    <xacro:property name = "forward_drive_arm_length" value = "0.75" />
    <xacro:property name = "forward_drive_arm_width" value = "0.05" />
    <xacro:property name = "forward_drive_arm_height" value = "0.005" />
    <xacro:property name = "horizontal_arm_length" value = "0.555" />
    <xacro:property name = "horizontal_arm_width" value = "0.05" />
    <xacro:property name = "horizontal_arm_height" value = "0.005" /> 
    <xacro:property name = "cylinder_radius" value = "0.015" />
    <xacro:property name = "cylinder_length" value = "0.18" />   

    <!-- Include Gazebo Parameters -->
    <xacro:include filename="$(find agbot_description)/urdf/agbot_arm_gazebo.xacro" />

    <!-- Include ros2_control Plugins -->
    <xacro:include filename="$(find agbot_description)/urdf/agbot_arm_ros2_control.xacro" />

    <xacro:include filename="$(find agbot_description)/urdf/common_properties.xacro" />

    <!-- Useful XACRO Variables (Properties) -->
    <xacro:property name="PI" value="3.14159265359" />
    <xacro:property name="effort" value="30.0" />
    <xacro:property name="velocity" value="10.0" />
    <xacro:property name="arm_scale" value="0.0015 0.0015 0.002"/>
    <xacro:property name="claw_scale" value="0.004 0.004 0.004"/>

    <!-- Useful Macros -->
    <xacro:macro name="default_inertia" params="mass">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                     iyy="1.0" iyz="0.0"
                     izz="1.0" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="default_transmission" params="name">
        <transmission name="${name}_transmission">
            <plugin>transmission_interface/SimpleTransmission</plugin>
            <actuator name="{name}_motor" role="actuator1"/>
            <joint name="{name}_joint" role="joint1">
                <mechanical_reduction>1.0</mechanical_reduction>
            </joint>
        </transmission>
    </xacro:macro>

    

    <!-- Link Descriptions -->
    <link name="world"/>

    <link name="base_link">
        <xacro:default_inertia mass="1.0"/>
        <visual>
            <origin xyz="-0.077 -0.075 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/basement.STL" scale="${arm_scale}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="-0.075 -.075 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/basement.STL" scale="${arm_scale}"/>
            </geometry> 
        </collision>      
    </link>

    <link name="base_plate">
        <xacro:default_inertia mass="0.1"/>
         <visual>
            <origin xyz="-0.059 -0.060 -0.121" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/base_plate.STL" scale="${arm_scale}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="-0.076 -0.0798 -0.121" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/base_plate.STL" scale="${arm_scale}"/>
            </geometry> 
        </collision>
    </link>   

    <link name="forward_drive_arm">
        <xacro:default_inertia mass="0.1"/>
        <visual>
            <origin xyz="-0.005 -0.006 0.38" rpy="0 ${PI / 2} ${PI / 2}"/>
            <geometry>
                <box size="${forward_drive_arm_length} ${forward_drive_arm_width} ${forward_drive_arm_height}" />
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin xyz="0.01 -0.006 0" rpy="0 ${PI / 2} ${PI / 2}"/>
            <geometry>
                <box size="${forward_drive_arm_length} ${forward_drive_arm_width} ${forward_drive_arm_height}" />
            </geometry> 
        </collision>
    </link>

    <link name = "elbow">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${PI / 2} 0"/>
            <geometry>
                <cylinder length = "${cylinder_length}" radius = "${cylinder_radius}" />
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${PI / 2} 0"/>
            <geometry>
                <cylinder length = "${cylinder_length}" radius = "${cylinder_radius}"  />
            </geometry> 
        </collision>
        <xacro:cylinder_inertia m = "0.05" r = "${cylinder_radius}" h = "${cylinder_length}" 
                               xyz = "0 0 0" rpy = "0 0 0"/>        
    </link>

    <link name="horizontal_arm">
        <xacro:default_inertia mass="0.1"/>
        <visual>
            <origin xyz="0 0 0.275" rpy="0 ${PI / 2} ${PI / 2}"/>
            <geometry>
                <box size="${horizontal_arm_length} ${horizontal_arm_width} ${horizontal_arm_height}" />
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0.275" rpy="0 ${PI / 2} ${PI / 2}"/>
            <geometry>
                <box size="${horizontal_arm_length} ${horizontal_arm_width} ${horizontal_arm_height}" />
            </geometry> 
        </collision>
    </link>   

    <link name = "wrist">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${PI / 2} 0"/>
            <geometry>
                <cylinder length = "${cylinder_length / 2}" radius = "${cylinder_radius}" />
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${PI / 2} 0"/>
            <geometry>
                <cylinder length = "${cylinder_length}" radius = "${cylinder_radius}"  />
            </geometry> 
        </collision>
        <xacro:cylinder_inertia m = "0.05" r = "${cylinder_radius}" h = "${cylinder_length}" 
                               xyz = "0 0 0" rpy = "0 0 0"/>        
    </link>    

    <link name="claw_support">
        <xacro:default_inertia mass="0.05"/>
        <visual>
            <origin xyz="-${cylinder_length/3.7} 0 0" rpy="0 -${PI/2} -${PI / 2}"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/claw_support.STL" scale="${claw_scale}"/>
            </geometry>
            <material name="pink"/>
        </visual>
        <collision>
            <origin xyz="-${cylinder_length/3.7} 0 0" rpy="0 -${PI/2} -${PI / 2}"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/claw_support.STL" scale="${claw_scale}"/>
            </geometry> 
        </collision>
    </link>    

    <link name="gripper_right">
        <xacro:default_inertia mass="0.01"/>
        <visual>
            <origin xyz="0.041 0 0.19" rpy="0 ${PI / 2} ${PI / 2}"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/right_finger.STL" scale="${claw_scale}"/>
            </geometry>
            <material name="purple"/>
        </visual>
        <collision>
            <origin xyz="0.041 0 0.19" rpy="0 ${PI / 2} ${PI / 2}"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/right_finger.STL" scale="${claw_scale}"/>
            </geometry> 
        </collision>
    </link>

    <link name="gripper_left">
        <xacro:default_inertia mass="0.01"/>
        <visual>
            <origin xyz="0.0147 0 0.19" rpy="0 ${PI / 2} ${PI / 2}"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/left_finger.STL" scale="${claw_scale}"/>
            </geometry>
            <material name="purple"/>
        </visual>
        <collision>
            <origin xyz="0.0147 0 0.19" rpy="0 ${PI / 2} ${PI / 2}"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/left_finger.STL" scale="${claw_scale}"/>
            </geometry> 
        </collision>
    </link>     

    <link name="arm_rgb_camera_optical" >
    </link> 

    <link name="arm_rgb_camera">
        <xacro:default_inertia mass="0.001"/>
        <visual>
            <origin xyz="-0.03 -0.055 0.05" rpy="0 ${PI/2} 0"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/pi_camera.STL" scale="${claw_scale}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 -.03 0" rpy="0 ${PI/2} 0"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/pi_camera.STL" scale="${claw_scale}"/>
            </geometry> 
        </collision>
    </link>

    <!-- Joint Descriptions -->
    <joint name="virtual_joint" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint> 

    <joint name ="base_joint" type="revolute">
        <parent link="base_link"/>
        <child link = "base_plate"/>
        <origin xyz="0 0 0.07"/>
        <axis xyz="0 0 1"/>
        <limit lower="-${PI}" upper="${PI}" 
               effort="${effort}" velocity="${velocity}"/>
    </joint> 

    <joint name="shoulder_joint" type="revolute">
        <parent link="base_plate"/>
        <child link="forward_drive_arm"/>
        <origin xyz="0 0 .075" rpy="-${PI/2} 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="0" upper="4.0" effort="${effort}" velocity="${velocity}"/>
    </joint>   
    
    <joint name = "shoulder_elbow_joint" type = "fixed">
        <parent link = "forward_drive_arm"/>
        <child link = "elbow"/>
        <origin xyz = "${(forward_drive_arm_width / 1.5) + 0.02} 0 ${forward_drive_arm_length}" rpy = "0 0 0"/>
    </joint>
    
    <joint name="elbow_joint" type="revolute">
        <parent link="elbow"/>
        <child link="horizontal_arm"/>
        <origin xyz="${cylinder_length/4} 0 0" rpy="-${PI} 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="-${PI}" upper="0" effort="${effort}" velocity="${velocity}"/>
    </joint>   
    
    <joint name = "elbow_forearm_joint" type = "fixed">
        <parent link = "horizontal_arm"/>
        <child link = "wrist"/>
        <origin xyz = "0 0 ${horizontal_arm_length}" rpy = "0 0 0"/>
    </joint>    

    <joint name="wrist_joint" type="revolute">
        <parent link="wrist"/>
        <child link="claw_support"/>
        <origin xyz="0 0 0" /> 
        <axis xyz="1 0 0"/>
        <limit lower="-${PI / 2}" upper="${PI / 2}" effort="${effort}" velocity="${velocity}"/>
    </joint>     

    <joint name="gripper_right_joint" type="revolute">
        <parent link="claw_support"/>
        <child link="gripper_right"/>
        <origin xyz="-0.033 -0.012 0.083"/> 
        <axis xyz="0 1 0"/>
        <limit lower="-${PI / 2}" upper="0.0" effort="${effort}" velocity="${velocity}"/>
    </joint> 

    <joint name="gripper_left_joint" type="revolute">
        <mimic joint="gripper_right_joint" multiplier="-1"/> 
        <parent link="claw_support"/>
        <child link="gripper_left"/>
        <origin xyz="0.038 -0.012 0.083"/> 
        <axis xyz="0 1 0"/>
        <limit lower="0.0" upper="${PI / 2}" effort="${effort}" velocity="${velocity}"/>
    </joint>   

    <joint name="arm_camera_optical_joint" type="fixed">
        <parent link="claw_support"/>
        <child link="arm_rgb_camera_optical"/>
        <origin xyz = "0 .13 0.085" rpy = "0 0 0" />
    </joint> 

    <joint name = "arm_rgb_camera_joint" type = "fixed" >        
        <parent link = "arm_rgb_camera_optical" />
        <child link = "arm_rgb_camera" />
        <origin xyz="0 0 0.015" rpy="0 -${PI/2} 0"/>
    </joint> 

 
    <xacro:default_transmission name="base_joint" />
    <xacro:default_transmission name="shoulder_joint" />
    <xacro:default_transmission name="elbow_joint" />
    <xacro:default_transmission name="wrist_joint" />
    <xacro:default_transmission name="gripper_right_joint" />


</robot>