<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="agbot">

    <!-- Include Gazebo Parameters -->
    <xacro:include filename="$(find agbot_description)/urdf/agbot_gazebo.xacro" />

    <xacro:include filename="$(find agbot_description)/urdf/agbot_common_properties.xacro" />    

    <xacro:include filename="$(find agbot_description)/urdf/agbot_ros2_control.xacro" />    
    
    <!-- Useful XACRO Variables (Properties) -->
    <xacro:property name="Pi" value="3.141592653589793238464" />
    <xacro:property name="effort" value="30.0" />
    <xacro:property name="velocity" value="10.0" />
    <xacro:property name="scale" value="0.0025 0.0025 0.0025"/>
    <xacro:property name="wheel_scale" value="0.006 0.006 0.006"/>    


    <!-- Useful Macros -->
    <xacro:macro name="default_inertia" params="mass">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                     iyy="1.0" iyz="0.0"
                     izz="1.0" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="default_transmission" params="name">
        <transmission name="transmission_${name}">
            <!-- <plugin>transmission_interface/DifferentialTransmission</plugin> -->
            <plugin>transmission_interface/SimpleTransmission</plugin>
            <actuator name="motor_${name}" role="actuator1"/>
            <joint name="${name}" role="joint1">
                <mechanical_reduction>1.0</mechanical_reduction>
            </joint>
        </transmission>
    </xacro:macro>

    <xacro:property name="base_length" value="1.8288" />
    <xacro:property name="base_width" value="1.8288" />
    <xacro:property name="base_height" value="0.762" /> 
    <xacro:property name="wheel_radius" value="0.06" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="mast_length" value="0.05" />
    <xacro:property name="mast_width" value="0.05" />
    <xacro:property name="mast_height" value="0.01" />
    <xacro:property name="caster_radius" value="0.06" />

    <link name = "base_footprint" /> 

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <material name="maroon"/>
        </visual>
        <collision>
            <geometry>
                 <box size="${base_length*1.1} ${base_width*1.1} ${base_height*1.1}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>           
        </collision>
        <xacro:box_inertia m="10.0" l="${base_length}" w="${base_width}" h="${base_height}"
                           xyz = "0 0 ${base_height/2}" rpy="0 0 0" />
    </link>   
    <gazebo reference="base_link">
        <material>Gazebo/White</material>
    </gazebo>      

    <link name="left_wheel_link" >
        <visual>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/left_tire.stl" scale="${wheel_scale}"/>
                <!-- <cylinder radius = "${wheel_radius}" length = "${wheel_length}" /> -->
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
            <material name = "black" />
        </visual>
        <collision>
                <geometry>
                    <mesh filename="file://$(find agbot_description)/meshes/left_tire.stl" scale="${wheel_scale}"/>
                    <!-- <cylinder radius = "${wheel_radius}" length = "${wheel_length}" /> -->
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />           
        </collision>
        <xacro:wheel_inertia m="1.0" r = "${wheel_radius}" h = "${wheel_length}"
                                xyz = "0 0 0" rpy = "${Pi/2.0} -${Pi/2.0} 0" />
    </link>
    <gazebo reference="left_wheel_link">
        <material>Gazebo/Black</material>
    </gazebo>     

    <link name="right_wheel_link" >
        <visual>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/right_tire.stl" scale="${wheel_scale}"/>
                <!-- <cylinder radius = "${wheel_radius}" length = "${wheel_length}" /> -->
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
            <material name = "black" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/right_tire.stl" scale="${wheel_scale}"/>
                <!-- <cylinder radius = "${wheel_radius}" length = "${wheel_length}" /> -->
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />           
        </collision>
        <xacro:wheel_inertia m="1.0" r = "${wheel_radius}" h = "${wheel_length}"
                                xyz = "0 0 0" rpy = "${Pi/2.0} -${Pi/2.0} 0" />
    </link>
    <gazebo reference="right_wheel_link">
        <material>Gazebo/Black</material>
    </gazebo>       

    <link name = "caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius = "${caster_radius}" />
            </geometry>
            <origin xyx = "${base_length / 3} 0 ${caster_radius}" rpy = "0 0 0" />
            <material name = "yellow" />            
        </visual>
        <collision>
            <geometry>
                <sphere radius = "${caster_radius}" />
            </geometry>
            <origin xyx = "${base_length / 3} 0 ${caster_radius}" rpy = "0 0 0" />
        </collision>
        <xacro:sphere_inertia m = "0.2" r = "${caster_radius}"
                              xyz = "${base_length / 3} 0 0" rpy = "0 0 0" />
    </link> 
    <gazebo reference="caster_wheel_link">
        <material>Gazebo/Yellow</material>
        <mu1 value="0.0001"/>
        <mu2 value="0.0001"/>
    </gazebo>       

    <link name="rgb_camera_optical" >
    </link> 

    <link name="rgb_camera">
        <xacro:default_inertia mass="0.001"/>
        <visual>
            <origin xyz="0 -0.035 0.035" rpy="0 ${Pi/2} 0"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/pi_camera.STL" scale="${scale}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0.2 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find agbot_description)/meshes/pi_camera.STL" scale="${scale}"/>
            </geometry> 
        </collision>
    </link>
    <gazebo reference="rgb_camera">
        <material>Gazebo/Green</material>
      </gazebo>     

    <link name="mast_link">
        <visual>
            <origin xyz="0 0 ${mast_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${mast_length} ${mast_width} ${mast_height}"/>
            </geometry>            
            <material name="pink"/>
        </visual>
        <collision>
            <geometry>
                 <box size="${mast_length} ${mast_width} ${mast_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>           
        </collision>
        <xacro:box_inertia m="0.005" l="${mast_length}" w="${mast_width}" h="${mast_height}"
                           xyz = "0 0 0" rpy="0 0 0" />
    </link> 
    <gazebo reference="mast_link">
        <material>Gazebo/Purple</material>   
    </gazebo>        
    
    <link name="laser_frame">       
    </link>    

    <!-- Joint Descriptions -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="-${base_length / 4.0} -${(base_width + wheel_length) / 2.0} 0.14" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="-${base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0.14" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint> 

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 0" rpy="0 0 0" />
    </joint>    

    <joint name="camera_optical_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rgb_camera_optical"/>
        <origin xyz = "${base_length/2} 0 ${base_height-0.02}" rpy = "0 0 0" />
    </joint> 

    <joint name = "rgb_camera_joint" type = "fixed" >        
        <parent link = "rgb_camera_optical" />
        <child link = "rgb_camera" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>    
    
    <joint name = "base_mast_joint" type = "fixed">
        <parent link = "base_link" />
        <child link = "mast_link" />
        <origin xyz="${((base_length/2)- 0.05)} 0 ${base_height}" rpy="0 0 0"/>
    </joint>

    <joint name="laser_joint" type="fixed">
        <parent link="mast_link"/>
        <child link="laser_frame"/>
        <origin xyz="0 0 ${mast_height + 0.02}" rpy="0 0 0"/>
    </joint>    

    <xacro:default_transmission name="base_right_wheel_joint" />
    <xacro:default_transmission name="base_left_wheel_joint" />
 


</robot>