controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    wheel_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

wheel_controller:
  ros__parameters:
    joints:
      - base_left_front_wheel_joint
      - base_right_front_wheel_joint
      - base_left_rear_wheel_joint
      - base_right_rear_wheel_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true
