initial_positions:
  arm_base_joint: 0.01
  base_rail_to_ mid_rail_joint: 0.01
  elbow_joint: 0.01
  gripper_right_joint: 0.01
  mid_rail_to_arm_car_joint: 0.01
  shoulder_joint: 0.01
  wrist_joint: 0.01