default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  arm_base_joint:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  base_rail_to_ mid_rail_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_left_joint:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper_right_joint:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  mid_rail_to_arm_car_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  shoulder_joint:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  wrist_joint:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0