controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

joint_state_controller:
  type: joint_state_controller/JointStateController

prismatic_joint_position_controller:
  type: effort_controllers/JointPositionController
  ros__parameters:
    joint: arm_base_to_arm_car_joint
    pid:
      p: 100.0
      i: 0.1
      d: 10.0
      i_clamp_min: -1.0
      i_clamp_max: 1.0

    command_timeout: 0.1 
    limits:
      lower: -0.381
      upper: 1.3716
